name: Build

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64, riscv64]
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tools-cache: false
          
      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "SHORT_GIT_SHA=$calculatedSha" >> $GITHUB_OUTPUT
    
      - uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: amd64,riscv64,arm64

      - uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/tiiuae/tii-fogsw-tools
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha
            type=raw,value=latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/${{ matrix.arch }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ghcr.io/tiiuae/tii-fogsw-tools:sha-${{ steps.vars.outputs.SHORT_GIT_SHA }}-${{ matrix.arch }}
          labels: ${{ steps.meta.outputs.labels }}

  create-manifest-list:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "SHORT_GIT_SHA=$calculatedSha" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create manifest list
        run: |
          docker buildx imagetools create \
          -t ghcr.io/tiiuae/tii-fogsw-tools:sha-${{ steps.vars.outputs.SHORT_GIT_SHA }} \
          ghcr.io/tiiuae/tii-fogsw-tools:sha-${{ steps.vars.outputs.SHORT_GIT_SHA }}-amd64 \
          ghcr.io/tiiuae/tii-fogsw-tools:sha-${{ steps.vars.outputs.SHORT_GIT_SHA }}-arm64 \
          ghcr.io/tiiuae/tii-fogsw-tools:sha-${{ steps.vars.outputs.SHORT_GIT_SHA }}-riscv64
